Controllers/Book InfoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BOOK_LIBRARY.Models;

namespace BOOK_LIBRARY.Controllers
{
    public class Book_InfoController : Controller
    {
        private BooksDBContext db = new BooksDBContext();

        // GET: Book_Info
        public ActionResult Index(string searchString)
        {
            var book_Infos = from c in db.Book_Infos
                             select c;


            if (!String.IsNullOrEmpty(searchString))
            {
                book_Infos = book_Infos.Where(s => s.Title.Contains(searchString));

            }
            
            return View(db.Book_Infos.ToList());
        }

        // GET: Book_Info/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book_Info book_Info = db.Book_Infos.Find(id);
            if (book_Info == null)
            {
                return HttpNotFound();
            }
            return View(book_Info);
        }

        // GET: Book_Info/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Book_Info/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,Author,genre,Plot,page,Rating")] Book_Info book_Info)
        {
            if (ModelState.IsValid)
            {
                db.Book_Infos.Add(book_Info);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(book_Info);
        }

        // GET: Book_Info/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book_Info book_Info = db.Book_Infos.Find(id);
            if (book_Info == null)
            {
                return HttpNotFound();
            }
            return View(book_Info);
        }

        // POST: Book_Info/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,Author,genre,Plot,page,Rating")] Book_Info book_Info)
        {
            if (ModelState.IsValid)
            {
                db.Entry(book_Info).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(book_Info);
        }

        // GET: Book_Info/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book_Info book_Info = db.Book_Infos.Find(id);
            if (book_Info == null)
            {
                return HttpNotFound();
            }
            return View(book_Info);
        }

        // POST: Book_Info/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Book_Info book_Info = db.Book_Infos.Find(id);
            db.Book_Infos.Remove(book_Info);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Book_Info/Create.cshtml
@model BOOK_LIBRARY.Models.Book_Info

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Book_Info</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Author, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Author, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Author, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.genre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.genre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.genre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Plot, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Plot, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Plot, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.page, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.page, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.page, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rating, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rating, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Book_Info/Delete.cshtml
@model BOOK_LIBRARY.Models.Book_Info

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Book_Info</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Author)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Author)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.genre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.genre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Plot)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Plot)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.page)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.page)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rating)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Book_Info/Details.cshtml
@model BOOK_LIBRARY.Models.Book_Info

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Book_Info</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Author)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Author)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.genre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.genre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Plot)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Plot)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.page)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.page)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rating)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Book_Info/Edit.cshtml
@model BOOK_LIBRARY.Models.Book_Info

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Book_Info</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Author, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Author, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Author, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.genre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.genre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.genre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Plot, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Plot, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Plot, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.page, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.page, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.page, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rating, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rating, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Book_Info/Index.cshtml
@model IEnumerable<BOOK_LIBRARY.Models.Book_Info>

@{
    ViewBag.Title = "Index";
}

<h2>Books</h2>

<button style="background-color:blueviolet">
    @Html.ActionLink("Create New", "Create")
</button>
@using (Html.BeginForm("Index", "Book_Info", FormMethod.Get))
{


    <p>
        Find by name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p>
}

<img src="https://pic.soundofmusic-shop.de/Book-LES-MIS-RABLES-From-Page-To-Stage-To-Screen-Benedict-Nightingale-.97993a.jpg" height="200" , width="200">
<img src="https://images-na.ssl-images-amazon.com/images/I/71Yl9WYd4+S.jpg" height="200" , width="200">
<img src="https://www.book.store.bg/lrgimg/17334/pod-igoto.jpg" height="200" , width="200">
<img src="https://static.nadirkitap.com/fotograf/37618/12/Kitap_20190202130736_37618_5.jpg" height="200" , width="200">
<img src="https://cdn.cimri.io/image/1000x1000/postermanyastiklalmarxcmposter_235182697.jpg" height="200" , width="200">

<table class="table">

    <tr>
        <th>
            @Html.ActionLink("Title", "Index", new { sortOrder = ViewBag.NameSortParm, Filter_Value = ViewBag.FilterValue })
        </th>
        <th>
            Author
        </th>
        <th>
            @Html.ActionLink("genre", "Index", new { sortOrder = ViewBag.DateSortParm, Filter_Value = ViewBag.FilterValue })
        </th>
        <th></th>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Author)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.genre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Plot)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.page)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Rating)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Author)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.genre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Plot)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.page)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rating)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>